name: IronSMP-Logo
version: 0.0.1
main: com.github.crafty5020.ironsmp_logo.MainPlugin
description: Auto spawns in all of the maps for the Iron SMP logo.
author: Iron Kigndom (Reis, Crafty5020)
website: https://github.com/Crafty5020/ironsmp_logo
api-version: '1.21.8'
